name: build

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16.0'

    - name: Install dependencies
      run: npm install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.100.2'
        extended: true

    - name: Deploy
      env:
        TZ: Asia/Shanghai
        DEPLOY_REPO: liawne/liawne.github.io
        DEPLOY_BRANCH: master
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        rm -rf ./public/*
        echo "## hugo --minify ##"
        hugo --minify
        echo "## cd public && git add . ##"
        cd public && git add .
        echo "## git config user.name  ##"
        git config user.name "liawne"
        echo "## git config user.email  ##"
        git config user.email "ruiwen5336@gmail.com"
        echo "## git commit ##
        git commit -m "Automated Deployment @ $(date '+%Y-%m-%d %H:%M:%S') ${TZ}"
        echo "## git push --force ##"
        git push --force "https://$PERSONAL_TOKEN@github.com/$DEPLOY_REPO" master:$DEPLOY_BRANCH
